#!/bin/bash

set -e

function path_from_url() {
    echo "$1" | rg '^.*ar-answers-in-search-models/static/(.*)$' -r '$1'
}

url="$1"
model_path="$(path_from_url "$url")"
out_path=models/"$model_path"

if [ -f "$out_path" ]; then
    exit 0
fi

valid_glb=1
curl "$url" --create-dirs -o "$out_path" || valid_glb=0
file "$out_path" | grep 'glTF binary model' || valid_glb=0
[ $valid_glb -eq 0 ] && echo "$path" >> errors && rm -f "$out_path"

echo "$url"
